import { Seeder } from 'typeorm-extension';
import { DataSource } from 'typeorm';
import { Dental, Prefecture, Category } from '../entities/dental.entity';

export default class DentalSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const dentalRepository = dataSource.getRepository(Dental);

    // trainerデータを挿入
    await dentalRepository.insert([
      {
        name: 'さくら歯科クリニック',
        address: '東京都新宿区西新宿1-2-3',
        phone: '03-1234-5678',
        email: 'sakura-dental@example.com',
        website: 'https://sakura-dental.com',
        description:
          '地域密着型の歯科医院です。一般歯科から矯正まで幅広く対応。',
        opening_hours: '9:00-18:00',
        access: '西新宿駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '山田 太郎',
        specialties: '一般歯科, 矯正歯科',
        parking: '有り（3台）',
        station: '西新宿駅',
        latitude: 35.6895,
        longitude: 139.6917,
        number_of_staff: 10,
        features: '最新のデジタル機器と丁寧なカウンセリング',
        equipment: 'デジタルレントゲン, CTスキャン',
        languages: '日本語, 英語',
        prefecture: Prefecture.TOKYO,
        category: Category.GENERAL,
      },
      {
        name: 'スマイルデンタル',
        address: '東京都渋谷区渋谷1-1-1',
        phone: '03-8765-4321',
        email: 'smile-dental@example.com',
        website: 'https://smile-dental.com',
        description: '最新設備を備えた清潔な院内。小児歯科も人気です。',
        opening_hours: '10:00-19:00',
        access: '渋谷駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '鈴木 花子',
        specialties: '小児歯科, 予防歯科',
        parking: '有り（2台）',
        station: '渋谷駅',
        latitude: 35.658,
        longitude: 139.7016,
        number_of_staff: 8,
        features: 'キッズスペース完備、痛みへの配慮',
        equipment: 'キッズチェア, 最新歯科機器',
        languages: '日本語',
        prefecture: Prefecture.TOKYO,
        category: Category.PEDIATRIC,
      },
      {
        name: '青葉歯科医院',
        address: '神奈川県横浜市青葉区青葉台1-2-3',
        phone: '045-9876-5432',
        email: 'aoba-dental@example.com',
        website: 'https://aoba-dental.com',
        description: '地域に根ざした家族向け歯科医院',
        opening_hours: '9:30-18:30',
        access: '青葉台駅 徒歩2分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '佐藤 健',
        specialties: '一般歯科, 予防歯科',
        parking: '有り（5台）',
        station: '青葉台駅',
        latitude: 35.5431,
        longitude: 139.5297,
        number_of_staff: 12,
        features: '家族全員の歯科ケア',
        equipment: 'デジタル診断機器, 最新治療機器',
        languages: '日本語',
        prefecture: Prefecture.KAGAWA,
        category: Category.GENERAL,
      },
      {
        name: '矯正クリニック東京',
        address: '東京都港区六本木7-8-9',
        phone: '03-5555-1212',
        email: 'kyousei-tokyo@example.com',
        website: 'https://kyousei-clinic.com',
        description: '最先端の矯正歯科治療を提供',
        opening_hours: '10:00-20:00',
        access: '六本木駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '中村 理恵',
        specialties: '矯正歯科',
        parking: '有り（4台）',
        station: '六本木駅',
        latitude: 35.663,
        longitude: 139.7317,
        number_of_staff: 6,
        features: '最新の矯正技術, 痛みの少ない治療',
        equipment: '3Dスキャナー, インビザライン',
        languages: '日本語, 英語',
        prefecture: Prefecture.TOKYO,
        category: Category.ORTHODONTICS,
      },
      {
        name: '口腔外科センター',
        address: '大阪府大阪市中央区大手前1-2-3',
        phone: '06-1234-5678',
        email: 'oral-surgery@example.com',
        website: 'https://oral-center.com',
        description: '高度な口腔外科治療を専門とする医院',
        opening_hours: '9:00-17:00',
        access: '大阪城公園駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '田中 一郎',
        specialties: '口腔外科',
        parking: '有り（6台）',
        station: '大阪城公園駅',
        latitude: 34.6872,
        longitude: 135.5258,
        number_of_staff: 8,
        features: '高度な外科的処置, 専門的治療',
        equipment: '最新手術機器, CT診断装置',
        languages: '日本語',
        prefecture: Prefecture.OSAKA,
        category: Category.ORAL,
      },
      {
        name: '小児歯科ハピネス',
        address: '愛知県名古屋市中区栄1-1-1',
        phone: '052-8888-9999',
        email: 'kids-dental@example.com',
        website: 'https://kids-happiness.com',
        description: '子供に優しい歯科医院',
        opening_hours: '10:00-19:00',
        access: '栄駅 徒歩1分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '伊藤 美咲',
        specialties: '小児歯科',
        parking: '有り（2台）',
        station: '栄駅',
        latitude: 35.1649,
        longitude: 136.885,
        number_of_staff: 5,
        features: 'キッズフレンドリー, 楽しい歯科体験',
        equipment: 'キッズチェア, 遊戯スペース',
        languages: '日本語',
        prefecture: Prefecture.AICHI,
        category: Category.PEDIATRIC,
      },
      {
        name: '予防歯科クリニック',
        address: '福岡県福岡市中央区天神1-2-3',
        phone: '092-7777-6666',
        email: 'yobo-dental@example.com',
        website: 'https://yobo-clinic.com',
        description: '予防歯科に特化した専門クリニック',
        opening_hours: '9:30-18:30',
        access: '天神駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '山本 浩二',
        specialties: '予防歯科',
        parking: '有り（3台）',
        station: '天神駅',
        latitude: 33.5903,
        longitude: 130.4017,
        number_of_staff: 7,
        features: '最新の予防歯科技術, 定期検診',
        equipment: 'プロフェッショナルクリーニング機器',
        languages: '日本語',
        prefecture: Prefecture.FUKUOKA, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '高齢者歯科ケアセンター',
        address: '京都府京都市中京区烏丸通り1-2-3',
        phone: '075-5555-4444',
        email: 'senior-dental@example.com',
        website: 'https://senior-care-dental.com',
        description: '高齢者に特化した歯科医療サービス',
        opening_hours: '9:00-17:00',
        access: '烏丸駅 徒歩2分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '木村 節子',
        specialties: '高齢者歯科',
        parking: '有り（4台）',
        station: '烏丸駅',
        latitude: 35.0116,
        longitude: 135.7556,
        number_of_staff: 6,
        features: '高齢者に優しい環境, 包括的ケア',
        equipment: '高齢者対応機器, リハビリ設備',
        languages: '日本語',
        prefecture: Prefecture.KYOTO, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '美容歯科クリニック',
        address: '兵庫県神戸市中央区三宮町1-1-1',
        phone: '078-3333-2222',
        email: 'beauty-dental@example.com',
        website: 'https://beauty-dental.com',
        description: '美容と歯科治療を融合したクリニック',
        opening_hours: '10:00-20:00',
        access: '三宮駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '岡田 美香',
        specialties: '美容歯科, ホワイトニング',
        parking: '有り（3台）',
        station: '三宮駅',
        latitude: 34.695,
        longitude: 135.1958,
        number_of_staff: 5,
        features: '最新の美容歯科技術, エステ感覚',
        equipment: 'ホワイトニング機器, レーザー治療機',
        languages: '日本語, 英語',
        prefecture: Prefecture.HYOGO,
        category: Category.GENERAL,
      },
      {
        name: '歯科・矯正クリニック',
        address: '北海道札幌市中央区大通西1-2-3',
        phone: '011-9999-8888',
        email: 'sapporo-dental@example.com',
        website: 'https://sapporo-dental.com',
        description: '総合的な歯科治療を提供',
        opening_hours: '9:30-18:30',
        access: '大通駅 徒歩1分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '渡辺 健太',
        specialties: '一般歯科, 矯正歯科',
        parking: '有り（5台）',
        station: '大通駅',
        latitude: 43.0618,
        longitude: 141.3545,
        number_of_staff: 10,
        features: '包括的な歯科治療, 最新技術',
        equipment: '3Dスキャナー, 最新診断機器',
        languages: '日本語',
        prefecture: Prefecture.HOKKAIDO,
        category: Category.GENERAL,
      },
      {
        name: '歯周病専門クリニック',
        address: '埼玉県さいたま市浦和区高砂1-2-3',
        phone: '048-7777-5555',
        email: 'shishubyou-clinic@example.com',
        website: 'https://shishubyou-clinic.com',
        description: '歯周病治療に特化した専門クリニック',
        opening_hours: '10:00-19:00',
        access: '浦和駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '小林 誠',
        specialties: '歯周病治療',
        parking: '有り（2台）',
        station: '浦和駅',
        latitude: 35.8569,
        longitude: 139.6568,
        number_of_staff: 6,
        features: '最新の歯周病治療, 包括的アプローチ',
        equipment: '歯周病診断機器, レーザー治療機',
        languages: '日本語',
        prefecture: Prefecture.SAITAMA,
        category: Category.GENERAL,
      },
      {
        name: '障がい者歯科センター',
        address: '千葉県千葉市中央区千葉港1-1-1',
        phone: '043-6666-7777',
        email: 'shogaisha-dental@example.com',
        website: 'https://shogaisha-dental.com',
        description: '障がいのある方のための歯科医療',
        opening_hours: '9:00-17:00',
        access: '千葉港駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '高橋 明子',
        specialties: '障がい者歯科',
        parking: '有り（4台）',
        station: '千葉港駅',
        latitude: 35.6072,
        longitude: 140.1165,
        number_of_staff: 8,
        features: '専門的ケア, バリアフリー環境',
        equipment: '特殊歯科治療機器, 安全設備',
        languages: '日本語',
        prefecture: Prefecture.CHIBA,
        category: Category.GENERAL,
      },
      {
        name: '審美歯科クリニック',
        address: '静岡県静岡市葵区追手町1-2-3',
        phone: '054-4444-3333',
        email: 'shinbi-dental@example.com',
        website: 'https://shinbi-dental.com',
        description: '最先端の審美歯科治療',
        opening_hours: '10:00-20:00',
        access: '静岡駅 徒歩2分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '石川 美智子',
        specialties: '審美歯科, インプラント',
        parking: '有り（3台）',
        station: '静岡駅',
        latitude: 34.9697,
        longitude: 138.3833,
        number_of_staff: 7,
        features: '最新の審美歯科技術, 自然な仕上がり',
        equipment: 'デジタルスマイルデザイン, 最新インプラント機器',
        languages: '日本語, 英語',
        prefecture: Prefecture.SHIZUOKA,
        category: Category.GENERAL,
      },
      {
        name: '歯科・インプラントクリニック',
        address: '愛知県豊田市西町1-2-3',
        phone: '0565-2222-1111',
        email: 'implant-clinic@example.com',
        website: 'https://implant-dental.com',
        description: 'インプラント治療に特化したクリニック',
        opening_hours: '9:30-18:30',
        access: '豊田市駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '加藤 博',
        specialties: 'インプラント治療',
        parking: '有り（6台）',
        station: '豊田市駅',
        latitude: 35.0995,
        longitude: 137.1586,
        number_of_staff: 9,
        features: '高度なインプラント技術, 精密な診断',
        equipment: '3Dインプラントシミュレーション, 最新外科機器',
        languages: '日本語',
        prefecture: Prefecture.AICHI,
        category: Category.GENERAL,
      },
      {
        name: '小児・矯正歯科クリニック',
        address: '広島県広島市中区紙屋町1-2-3',
        phone: '082-8888-7777',
        email: 'kids-orthodontics@example.com',
        website: 'https://kids-ortho-clinic.com',
        description: '子供の歯並びと成長をサポート',
        opening_hours: '10:00-19:00',
        access: '紙屋町駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '森本 由美',
        specialties: '小児歯科, 矯正歯科',
        parking: '有り（2台）',
        station: '紙屋町駅',
        latitude: 34.3963,
        longitude: 132.4595,
        number_of_staff: 6,
        features: '成長に合わせた矯正治療, 子供に優しい環境',
        equipment: '小児矯正機器, デジタル診断システム',
        languages: '日本語',
        prefecture: Prefecture.HIROSHIMA,
        category: Category.PEDIATRIC,
      },
      {
        name: '歯科リハビリテーションクリニック',
        address: '長野県長野市大字南長野1-2-3',
        phone: '026-5555-6666',
        email: 'rehab-dental@example.com',
        website: 'https://rehab-dental.com',
        description: '歯科リハビリテーションに特化したクリニック',
        opening_hours: '9:00-17:00',
        access: '長野駅 徒歩4分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '西山 健一',
        specialties: '歯科リハビリテーション',
        parking: '有り（4台）',
        station: '長野駅',
        latitude: 36.6513,
        longitude: 138.1909,
        number_of_staff: 7,
        features: '包括的なリハビリテーション, 個別アプローチ',
        equipment: '歯科リハビリ機器, 最新診断システム',
        languages: '日本語',
        prefecture: Prefecture.NAGANO,
        category: Category.GENERAL,
      },
      {
        name: '歯科・口腔ケアクリニック',
        address: '新潟県新潟市中央区万代1-2-3',
        phone: '025-3333-4444',
        email: 'oral-care-clinic@example.com',
        website: 'https://oral-care-clinic.com',
        description: '包括的な口腔ケアを提供',
        opening_hours: '10:00-19:00',
        access: '万代駅 徒歩2分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '斎藤 理恵',
        specialties: '口腔ケア, 予防歯科',
        parking: '有り（3台）',
        station: '万代駅',
        latitude: 37.9161,
        longitude: 139.0236,
        number_of_staff: 5,
        features: '総合的な口腔ケア, 予防医療',
        equipment: '最新口腔診断機器, クリーニング設備',
        languages: '日本語',
        prefecture: Prefecture.NIIGATA, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・睡眠時無呼吸症候群クリニック',
        address: '岐阜県岐阜市柳ヶ瀬通り1-2-3',
        phone: '058-7777-8888',
        email: 'sleep-apnea-clinic@example.com',
        website: 'https://sleep-apnea-dental.com',
        description: '睡眠時無呼吸症候群の治療に特化',
        opening_hours: '9:30-18:30',
        access: '柳ヶ瀬駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '中島 健太郎',
        specialties: '睡眠時無呼吸症候群治療',
        parking: '有り（2台）',
        station: '柳ヶ瀬駅',
        latitude: 35.4064,
        longitude: 136.7628,
        number_of_staff: 6,
        features: '専門的な睡眠時無呼吸治療, 包括的アプローチ',
        equipment: '睡眠診断機器, 専門治療機器',
        languages: '日本語',
        prefecture: Prefecture.GIFU, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・スポーツ歯科クリニック',
        address: '三重県津市丸之内1-2-3',
        phone: '059-6666-5555',
        email: 'sports-dental@example.com',
        website: 'https://sports-dental-clinic.com',
        description: 'アスリートのための歯科医療',
        opening_hours: '10:00-20:00',
        access: '津駅 徒歩4分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '山崎 大輔',
        specialties: 'スポーツ歯科',
        parking: '有り（4台）',
        station: '津駅',
        latitude: 34.7303,
        longitude: 136.5066,
        number_of_staff: 7,
        features: 'アスリート向けカスタムマウスガード, スポーツ歯科専門',
        equipment: 'スポーツ歯科診断機器, 3Dスキャナー',
        languages: '日本語',
        prefecture: Prefecture.MIE, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・摂食嚥下リハビリクリニック',
        address: '石川県金沢市広坂1-2-3',
        phone: '076-4444-3333',
        email: 'swallowing-rehab@example.com',
        website: 'https://swallowing-dental.com',
        description: '摂食嚥下リハビリテーションに特化',
        opening_hours: '9:00-17:00',
        access: '金沢駅 徒歩5分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '川田 美智子',
        specialties: '摂食嚥下リハビリテーション',
        parking: '有り（3台）',
        station: '金沢駅',
        latitude: 36.5813,
        longitude: 136.6472,
        number_of_staff: 6,
        features: '専門的な摂食嚥下リハビリ, 多職種連携',
        equipment: '嚥下診断機器, リハビリ設備',
        languages: '日本語',
        prefecture: Prefecture.ISHIKAWA, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・緩和ケアクリニック',
        address: '和歌山県和歌山市本町1-2-3',
        phone: '073-5555-6666',
        email: 'palliative-dental@example.com',
        website: 'https://palliative-dental-clinic.com',
        description: '歯科医療における緩和ケアに特化',
        opening_hours: '10:00-19:00',
        access: '和歌山駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '橋本 一郎',
        specialties: '緩和歯科ケア',
        parking: '有り（2台）',
        station: '和歌山駅',
        latitude: 34.2304,
        longitude: 135.1706,
        number_of_staff: 5,
        features: '痛みに配慮した歯科治療, 心のケア',
        equipment: '緩和ケア専門機器, 痛み軽減設備',
        languages: '日本語',
        prefecture: Prefecture.WAKAYAMA, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・遺伝子診断クリニック',
        address: '山梨県甲府市丸の内1-2-3',
        phone: '055-7777-8888',
        email: 'genetic-dental@example.com',
        website: 'https://genetic-dental-clinic.com',
        description: '遺伝子診断を取り入れた歯科医療',
        opening_hours: '9:30-18:30',
        access: '甲府駅 徒歩4分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '小野 智子',
        specialties: '遺伝子診断, 予防歯科',
        parking: '有り（3台）',
        station: '甲府駅',
        latitude: 35.663,
        longitude: 138.5686,
        number_of_staff: 7,
        features: '遺伝子レベルの診断, 個別化医療',
        equipment: '遺伝子検査機器, 最新診断システム',
        languages: '日本語',
        prefecture: Prefecture.YAMANASHI, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・再生医療クリニック',
        address: '富山県富山市新総曲輪1-2-3',
        phone: '076-8888-9999',
        email: 'regenerative-dental@example.com',
        website: 'https://regenerative-dental-clinic.com',
        description: '再生医療を取り入れた歯科治療',
        opening_hours: '10:00-19:00',
        access: '富山駅 徒歩2分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '藤原 健一',
        specialties: '再生歯科医療',
        parking: '有り（4台）',
        station: '富山駅',
        latitude: 36.6958,
        longitude: 137.2136,
        number_of_staff: 8,
        features: '最先端の再生医療技術, 組織再生',
        equipment: '再生医療機器, 幹細胞培養設備',
        languages: '日本語',
        prefecture: Prefecture.TOYAMA, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
      {
        name: '歯科・デジタル歯科クリニック',
        address: '福井県福井市大手1-2-3',
        phone: '0776-5555-4444',
        email: 'digital-dental@example.com',
        website: 'https://digital-dental-clinic.com',
        description: 'デジタル技術を駆使した歯科医療',
        opening_hours: '9:00-17:00',
        access: '福井駅 徒歩3分',
        image_url: 'https://placehold.jp/400x300.png',
        director: '松本 光',
        specialties: 'デジタル歯科治療',
        parking: '有り（3台）',
        station: '福井駅',
        latitude: 36.0678,
        longitude: 136.2224,
        number_of_staff: 6,
        features: '最新デジタル技術, 精密な診断と治療',
        equipment: 'CAD/CAM, 3Dスキャナー',
        languages: '日本語',
        prefecture: Prefecture.FUKUI, // 修正: 文字列から列挙型に変更
        category: Category.GENERAL, // 修正: 文字列から列挙型に変更
      },
    ]);
  }
}
